### ISSUE TITLE
Ideal Unit Test Cases

### ISSUE THREAD

**Issue by clohr** [clohr/safeguard#1]
@davidchase Thoughts on using something like Zombie with a static page and utilize the client-side DOM or should we continue to mock it as seen in the current tests?

**Comment by davidchase** [comment]
yeah dealing with the DOM and unit tests is a bit of a pain..

i think its a matter of preference though.. that being said my personal pref would be to not introduce things like zombie it seems a bit much however the new one seems easy to use.. again matter of preference i guess.

personally i would separate the method from the DOM so essentially you would be testing functionality that method is expected to do. essentially the pattern that i used for testing my cookie manager.

depending how interested you are in creating tests you could always build up your own DOM and then crawl it to test various nodes.
